@extends('layouts.app')
@section('title', __('auth.setup_title'))

@section('content')
    <h1>{{ __('auth.setup_title') }}</h1>

    @if (session('status') === 'two-factor-authentication-enabled')
        <x-alert variant="success" :title="__('auth.secret_generated')">{{ __('auth.secret_generated_body') }}</x-alert>
    @else
        <x-flash />
    @endif

    @if ($errors->any())
        <x-alert variant="danger" :title="__('officer.action_impossible')">
            <ul class="alert__list">@foreach ($errors->all() as $m)<li>{{ $m }}</li>@endforeach</ul>
        </x-alert>
    @endif

    @if ($required && ! $confirmed)
        <x-alert variant="danger" :title="__('auth.required_title')">
            {{ __('auth.required_body') }}
        </x-alert>
    @endif

    <x-card :title="__('auth.state')">
        <p>
            @if ($confirmed)
                <span class="badge badge--success">{{ __('auth.state_confirmed') }}</span>
            @elseif ($enabled)
                <span class="badge badge--waiting">{{ __('auth.state_pending') }}</span>
            @else
                <span class="badge badge--neutral">{{ __('auth.state_none') }}</span>
            @endif
        </p>

        @if (! $enabled)
            <p>{{ __('auth.need_app') }}</p>
            <form method="POST" action="{{ route('two-factor.enable') }}">
                @csrf
                <x-button type="submit" variant="primary">{{ __('auth.set_up_now') }}</x-button>
            </form>
        @endif
    </x-card>

    @if ($qrCode)
        <x-card :title="__('auth.scan_title')">
            <div class="qr-wrap">{!! $qrCode !!}</div>
            {{--
                Documented exception to the ban on {!! !!} (4.5 of the brief).
                The SVG is generated by Fortify from the account's secret: it
                holds no user-supplied data, so no injection vector. Escaping it
                would simply make it unreadable.
            --}}
        </x-card>

        <x-card :title="__('auth.confirm_title')">
            <form method="POST" action="{{ route('two-factor.confirm') }}">
                @csrf
                <x-field name="code" :label="__('auth.twofa_code')" required
                         inputmode="numeric" pattern="[0-9]*" autocomplete="one-time-code"
                         :error="$errors->first('code')" />
                <x-button type="submit" variant="primary">{{ __('auth.confirm') }}</x-button>
            </form>
        </x-card>
    @endif

    @if ($confirmed)
        <x-card :title="__('auth.recovery_title')">
            <p>{{ __('auth.recovery_body') }}</p>

            @if ($recoveryCodes)
                <div class="recovery-codes">
                    @foreach ($recoveryCodes as $code)<span>{{ $code }}</span>@endforeach
                </div>
            @endif

            <form method="POST" action="{{ route('two-factor.recovery-codes') }}" class="u-stack-top">
                @csrf
                <x-button type="submit" variant="secondary">{{ __('auth.recovery_regenerate') }}</x-button>
            </form>
        </x-card>
    @endif

    @if ($confirmed && $peutEnrolerUnAppareil)
        <x-card :title="__('auth.device_title')">
            <p>{{ __('auth.device_body') }}</p>
            <p class="u-note">
                {!! __('auth.device_privacy', ['strong' => '<strong>'.e(__('auth.device_privacy_strong')).'</strong>']) !!}
            </p>

            @if ($appareils->isNotEmpty())
                {{-- THE ONLY SCREEN TABLE WITHOUT A SCROLL REGION (D-074).

                     On a phone it overflowed: the "Action" column, and so the
                     "Revoke" button, ran off the screen with no way to reach
                     it. A mayor whose phone was LOST and who has only a phone
                     to hand could not revoke the lost device. That is the
                     emergency action of this page. --}}
                <div class="table-wrap" tabindex="0" role="group" aria-label="{{ __('auth.devices_aria') }}">
                <table>
                    <caption class="visually-hidden">{{ __('auth.devices_aria') }}</caption>
                    <thead><tr>
                        <th scope="col">{{ __('auth.device_column') }}</th>
                        <th scope="col">{{ __('auth.enrolled_on') }}</th>
                        <th scope="col">{{ __('auth.last_signature') }}</th>
                        <th scope="col">{{ __('common.action') }}</th>
                    </tr></thead>
                    <tbody>
                        @foreach ($appareils as $appareil)
                            <tr>
                                <td data-label="{{ __('auth.device_column') }}">{{ $appareil->label }}</td>
                                <td data-label="{{ __('auth.enrolled_on') }}">{{ $appareil->created_at?->translatedFormat('d/m/Y') }}</td>
                                <td data-label="{{ __('auth.last_signature') }}">{{ $appareil->last_used_at?->translatedFormat('d/m/Y H:i') ?? __('common.never') }}</td>
                                <td data-label="{{ __('common.action') }}">
                                    <form method="POST" action="{{ route('devices.destroy', $appareil) }}">
                                        @csrf
                                        @method('DELETE')
                                        <x-button type="submit" variant="danger">{{ __('auth.revoke') }}</x-button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                </div>
            @else
                <p class="u-note">{{ __('auth.no_devices') }}</p>
            @endif

            {{--
                `hidden` by default: the script reveals this only if the browser
                knows WebAuthn AND the page is served in a secure context.
                Offering an impossible action is worse than not offering it.
            --}}
            <div data-webauthn hidden class="u-stack-top">
                <form method="POST" action="{{ route('devices.store') }}" id="form-enrolement-appareil">
                    @csrf
                    <input type="hidden" name="credential" id="credential">

                    <x-field name="label" :label="__('auth.device_name')"
                             :hint="__('auth.device_name_hint')"
                             :value="old('label')"
                             :error="$errors->first('label')" />

                    <x-button type="button" variant="primary" id="bouton-enroler-appareil"
                              data-options-url="{{ route('devices.options') }}">
                        {{ __('auth.enrol_device') }}
                    </x-button>
                </form>
                <p id="message-appareil" class="u-note"></p>
            </div>
        </x-card>
    @endif
@endsection
